### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by bPCioSubstituteOPfromLastWeek** [kekw-420/TestRepo420#1]
Upload the JS itself here as well.

I'll update the comments at the beginning to remove all of the pony shit, we can slowly start adding more template images to it.

Good fucking work man.

**Comment by kekw-420** [comment]
script is minimap.js
its more about the picture itself(miku.png) and templates.json, those are the things that are needed for the script to work

**Comment by bPCioSubstituteOPfromLastWeek** [comment]
I know. I made a pull request and edited the header to remove the pony stuff.
We can edit here for now. Once the templates get spicier, we'll probably need to move.
Add me as a contributor for now, we'll figure it out. I didn't sleep either, probably time I get on that.
