### ISSUE TITLE
Remove GitHub dependency(make it decentralized)

### ISSUE THREAD

**Issue by kekw-420** [kekw-420/TestRepo420#3]
Some people see our project as offensive, and might try to take it down. To combat this, we should remove the GitHub dependency that our project currently has.

CC from **internal messageboard system :-)**

`Yeah
About hotlinking, im no TamperMonkey expert, but it needs @connect raw.githubusercontent.com to access the files. If you can bypass that(maybe @connect * or something) then you can just edit line 394, make it have no prefix and just set the filename to the link`

**Comment by bPCioSubstituteOPfromLastWeek** [comment]
https://github.com/kekw-420/TestRepo420/tree/bPCioSubstituteOPfromLastWeek-test

**Comment by bPCioSubstituteOPfromLastWeek** [comment]
Feline Package Cute TOS - this is the TL;DR. the full TOS is basically "they can do what they want."
>Do not upload: Child pornography, viruses/malware, entire episodes of anime, or full length episodes of TV shows, heavy gore, sexualized depictions of minors, bestiality and sexual violence. I will purge your account/uploads if anything you upload violates these rules. See our Acceptable Use Policy and Terms of Service for more info.

**Comment by kekw-420** [comment]
Added config menu to it, everything seems to work. Left is to make some instructions so people can actually use the damn thing. Also somehow glitched out github, apparently invalid-email-address commited it lulz

**Comment by kekw-420** [comment]
I think its done :-)
